version: '3'

services:
  jupyter-data:
    build: .
    
    ports:
      - "8888:8888"
    volumes:
      - ~/.aws/:/home/.aws/:ro
     - /home/ubuntu/notebooks:/home/jovyan/work
    environment:
      - CHOWN_HOME=yes
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes

    command: "start.sh jupyter notebook --NotebookApp.token='Nube2021' --notebook-dir=/home/jovyan/work --ResourceUseDisplay.mem_limit=128000 --allow-root"